export const colData = [
    {collection: "Syracuse",},
    {collection: "West Berlin",},
    {collection: "Palermo",},
    {collection: "San Simeon",},
    {collection: "B.M. ",},
    {collection: "Tirana",},
    {collection: "Basel ",},
    {collection: "Private coll.",},
    {collection: "Laon ",},
    {collection: "Udine",},
    {collection: "Vatican",},
    {collection: "Heligoland ",},
    {collection: "Kropatschek",},
    {collection: "Warsaw",},
    {collection: "Madrid",},
    {collection: "Prado",},
    {collection: "Syracuse",},
    {collection: "Lipari",},
    {collection: "Ragusa",},
    {collection: "Geneva Market ",},
    {collection: "Koutoulakis-Zimmermann",},
    {collection: "Zurich Market",},
    {collection: "Arete",},
    {collection: "Nocera",},
    {collection: "Madrid ",},
    {collection: "Gela",},
    {collection: "Cefalh",},
    {collection: "Bari",},
    {collection: "Baranello",},
    {collection: "Museo Archeologico",},
    {collection: "Frankfurt Market",},
    {collection: "Bern",},
    {collection: "Locri",},
    {collection: "Melbourne",},
    {collection: "Canberra ",},
    {collection: "Reggio Cal.",},
    {collection: "B.M.",},
    {collection: "Louvre",},
    {collection: "Berlin",},
    {collection: "Basel Market",},
    {collection: "Bologna",},
    {collection: "Tischbein",},
    {collection: "Cefalu",},
    {collection: "Naples",},
    {collection: "Zurich",},
    {collection: "Dublin ",},
    {collection: "University College",},
    {collection: "Brisbane",},
    {collection: "University of Queensland",},
    {collection: "B.M.",},
    {collection: "Cefalu",},
    {collection: "Hasselmann",},
    {collection: "Catania",},
    {collection: "Louvre",},
    {collection: "S. Agata",},
    {collection: "Rainone",},
    {collection: "Taranto",},
    {collection: "New York Market ",},
    {collection: "Atlantis Gallery",},
    {collection: "Gela",},
    {collection: "North German",},
    {collection: "Leningrad",},
    {collection: "Zurich",},
    {collection: "Dublin ",},
    {collection: "University College",},
    {collection: "Brisbane",},
    {collection: "University of Queensland",},
    {collection: "B.M.",},
    {collection: "Cefalu",},
    {collection: "Hasselmann",},
    {collection: "Catania",},
    {collection: "Louvre",},
    {collection: "S. Agata",},
    {collection: "Rainone",},
    {collection: "Taranto",},
    {collection: "New York Market",},
    {collection: "Atlantis Gallery",},
    {collection: "Gela",},
    {collection: "North German",},
    {collection: "Leningrad",},
]