export const provData = [
    {provenance: "Palazzuolo",},
    {provenance: "Fusco necropolis",},
    {provenance: "Monte Adranone, T. 1",},
    {provenance: "Acropolis",},
    {provenance: "T. 24",},
    {provenance: "Cumae",},
    {provenance: "S. Venera (11 May 1976)",},
    {provenance: "Nola (Blacas Tomb) ",},
    {provenance: "Dyrrachium",},
    {provenance: "Lentini",},
    {provenance: "T. 1050",},
    {provenance: "T. 1675a",},
    {provenance: "T. 614 ",},
    {provenance: "Gela",},
    {provenance: "Lipari",},
    {provenance: "Dr. C. Clairmont. 6 x 10-5",},
    {provenance: "Locri",},
    {provenance: "Locri, T. 892 ",},
    {provenance: "Nola",},
    {provenance: "Viterbo",},
    {provenance: "Capua",},
    {provenance: "Naples, Via Cirillo, T. 3",},
    {provenance: "Scoglitti, T. 277",},
    {provenance: "Sicily",},
    {provenance: "Castelcapuano, T. 16",},
    {provenance: "Sicily (Messina ?)",},
    {provenance: "T. 1675 A",},
    {provenance: "T. 974",},
    {provenance: "T. 921",},
    {provenance: "T. 367",},
    {provenance: "Taranto",},
    {provenance: "Syracuse",},
]