export const shapeData = [
    {shape: "Alabastron",},
    {shape: "Alabastron",},
    {shape: "Alabastron(?) fragment",},
    {shape: "Alabastron(?) fragments",},
    {shape: "Alabastron fragment",},
    {shape: "Alabastron fragments",},
    {shape: "Amphora",},
    {shape: "Amphora(?)",},
    {shape: "Amphora(?) fragment",},
    {shape: "Amphora(?) fragments",},
    {shape: "Amphora a",},
    {shape: "Amphora a(?)",},
    {shape: "Amphora a fragment",},
    {shape: "Amphora a fragments",},
    {shape: "Amphora b",},
    {shape: "Amphora b fragment",},
    {shape: "Amphora b fragments",},
    {shape: "Amphora c",},
    {shape: "Amphora c fragment",},
    {shape: "Amphora fragment",},
    {shape: "Amphora fragments",},
    {shape: "Amphora panathenaic shape fragments",},
    {shape: "Amphora psykter",},
    {shape: "Amphora, bail",},
    {shape: "Amphora, belly-handled",},
    {shape: "Amphora, belly-handled",},
    {shape: "Neck Amphora",},
    {shape: "Amphora, neck",},
    {shape: "Amphora, neck(?)",},
    {shape: "Amphora, neck(?) fragment",},
    {shape: "Amphora, neck(?) frr",},
    {shape: "Amphora, neck and lid",},
    {shape: "Amphora, neck fragment",},
    {shape: "Amphora, neck fragments",},
    {shape: "Amphora, panathenaic shape",},
    {shape: "Amphora, panathenaic shape, fragment",},
    {shape: "Amphora, panathenaic shape, fragments",},
    {shape: "Amphora, pointed",},
    {shape: "Amphora, shoulder-handled",},
    {shape: "Amphora, stamnoid",},
    {shape: "Amphoriskos",},
    {shape: "Amphoriskos fragment",},
    {shape: "Aryballos",},
    {shape: "Aryballos(?) fragment",},
    {shape: "Aryballos fragment",},
    {shape: "Aryballos fragments",},
    {shape: "Aryballos, ovoid",},
    {shape: "Aryballos, ovoid fragment",},
    {shape: "Aryballos, pointed",},
    {shape: "Askos",},
    {shape: "Askos(?) fr",},
    {shape: "Askos fragment",},
    {shape: "Askos fragments",},
    {shape: "Askos, double",},
    {shape: "Astragalos",},
    {shape: "Astragalos fragment",},
    {shape: "Bail vase",},
    {shape: "Bail vase fragment",},
    {shape: "Bail-vase",},
    {shape: "Ball",},
    {shape: "Balsamarion",},
    {shape: "Basin",},
    {shape: "Basket",},
    {shape: "Beaker",},
    {shape: "Beaker fragment",},
    {shape: "Bell",},
    {shape: "Bell-krater",},
    {shape: "Bell-kraters",},
    {shape: "Bell-krater (Fragmentary)",},
    {shape: "Biconical urn",},
    {shape: "Bobbin",},
    {shape: "Bobbin fragment",},
    {shape: "Boeotian bird cup",},
    {shape: "Bolsal",},
    {shape: "Bolsal fragments",},
    {shape: "Bottle",},
    {shape: "Bowl",},
    {shape: "Bowl",},
    {shape: "Bowl fragment",},
    {shape: "Bowl fragments",},
    {shape: "Brazier",},
    {shape: "Calyx-krater",},
    {shape: "Calyx-kraters",},
    {shape: "Canopic jar",},
    {shape: "Chalice",},
    {shape: "Chalice fragment",},
    {shape: "Chalice fragments",},
    {shape: "Chous",},
    {shape: "Chous fr",},
    {shape: "Chous fragment",},
    {shape: "Chous fragments",},
    {shape: "Cista",},
    {shape: "Columbus alabastron",},
    {shape: "Cruet",},
    {shape: "Cup",},
    {shape: "Cup(?)",},
    {shape: "Cup(?) co",},
    {shape: "Cup(?) fragment",},
    {shape: "Cup(?) frr",},
    {shape: "Cup(?) lmb fr",},
    {shape: "Cup ?",},
    {shape: "Cup a",},
    {shape: "Cup a(?) fr",},
    {shape: "Cup a(?) frr",},
    {shape: "Cup a fragment",},
    {shape: "Cup a fragments",},
    {shape: "Cup b",},
    {shape: "Cup b(?) fr",},
    {shape: "Cup b fragment",},
    {shape: "Cup b fragments",},
    {shape: "Cup c",},
    {shape: "Cup c(?) fr",},
    {shape: "Cup c(?) fragments",},
    {shape: "Cup c fragment",},
    {shape: "Cup c fragments",},
    {shape: "Cup chalcidising",},
    {shape: "Cup covered",},
    {shape: "Cup d(?) frr",},
    {shape: "Cup droop",},
    {shape: "Cup droop  fragment",},
    {shape: "Cup droop(?) fragment",},
    {shape: "Cup droop(?) fragments",},
    {shape: "Cup droop fragments",},
    {shape: "Cup fragment",},
    {shape: "Cup fragments",},
    {shape: "Cup fragments",},
    {shape: "Cup kassel",},
    {shape: "Cup kassel(?) fragment",},
    {shape: "Cup kassel fragment",},
    {shape: "Cup kassel fragments",},
    {shape: "Cup little master(?) fragments",},
    {shape: "Cup little master band",},
    {shape: "Cup little master band(?) fragment",},
    {shape: "Cup little master band(?) fragments",},
    {shape: "Cup little master band fragment",},
    {shape: "Cup little master band fragments",},
    {shape: "Cup little master fragment",},
    {shape: "Cup little master fragments",},
    {shape: "Cup little master lip",},
    {shape: "Cup little master lip(?) fragment",},
    {shape: "Cup little master lip(?) fragments",},
    {shape: "Cup little master lip fragment",},
    {shape: "Cup little master lip fragments",},
    {shape: "Cup lml(?)",},
    {shape: "Cup or sky frr",},
    {shape: "Cup siana",},
    {shape: "Cup siana(?) fragment",},
    {shape: "Cup siana(?) fragments",},
    {shape: "Cup siana fragment",},
    {shape: "Cup siana fragments",},
    {shape: "Cup sky(?) fr",},
    {shape: "Cup skyphos",},
    {shape: "Cup skyphos fragment",},
    {shape: "Cup skyphos fragments",},
    {shape: "Cup stemless",},
    {shape: "Cup stemless(?) fragment",},
    {shape: "Cup stemless fragment",},
    {shape: "Cup stemless fragments",},
    {shape: "Cup stemless little master band",},
    {shape: "Cup stemless little master band fragment",},
    {shape: "Cup stemless little master band fragments",},
    {shape: "Cup, one-handled",},
    {shape: "Cylinder",},
    {shape: "Die",},
    {shape: "Dinos",},
    {shape: "Dinos(?) fr",},
    {shape: "Dinos fragment",},
    {shape: "Dinos fragments",},
    {shape: "Disc",},
    {shape: "Disc fragment",},
    {shape: "Dish",},
    {shape: "Dish fragment",},
    {shape: "Dish fragments",},
    {shape: "Dolium",},
    {shape: "Double vase",},
    {shape: "Epichysis",},
    {shape: "Epinetron",},
    {shape: "Epinetron(?) fragment",},
    {shape: "Epinetron fragment",},
    {shape: "Epinetron fragments",},
    {shape: "Face-urn",},
    {shape: "Feeder",},
    {shape: "Feeder fragment",},
    {shape: "Fiasca",},
    {shape: "Fig kantharos fragments",},
    {shape: "Figure ask feeder",},
    {shape: "Figure vase",},
    {shape: "Figure vase(?) fragment",},
    {shape: "Figure vase(?) fragments",},
    {shape: "Figure vase alabastron",},
    {shape: "Figure vase amphoriskos",},
    {shape: "Figure vase aryballos",},
    {shape: "Figure vase aryballos fragment",},
    {shape: "Figure vase aryballos fragments",},
    {shape: "Figure vase askos",},
    {shape: "Figure vase askos fragment",},
    {shape: "Figure vase fragment",},
    {shape: "Figure vase fragments",},
    {shape: "Figure vase kantharos",},
    {shape: "Figure vase kantharos(?) fragment",},
    {shape: "Figure vase kantharos fragment",},
    {shape: "Figure vase lekythos",},
    {shape: "Figure vase lekythos fragment",},
    {shape: "Figure vase mug",},
    {shape: "Figure vase mug fragments",},
    {shape: "Figure vase oinochoe",},
    {shape: "Figure vase oinochoe(?) fragment",},
    {shape: "Figure vase oinochoe fragment",},
    {shape: "Figure vase oinochoe fragments",},
    {shape: "Figure vase, guttus",},
    {shape: "Fish plate fragment",},
    {shape: "Fish-plate",},
    {shape: "Flask",},
    {shape: "Fragment",},
    {shape: "Fragments",},
    {shape: "Funnel",},
    {shape: "Granary",},
    {shape: "Guttus",},
    {shape: "Guttus fragment",},
    {shape: "House urn",},
    {shape: "Hydria",},
    {shape: "Hydria(?) fragment",},
    {shape: "Hydria(?) fragments",},
    {shape: "Hydria fragment",},
    {shape: "Hydria (Of Special Shape)",},
    {shape: "Hydria fragments",},
    {shape: "Hydriai",},
    {shape: "Idol",},
    {shape: "Idol fragment",},
    {shape: "Incense burner",},
    {shape: "Incense burner fragment",},
    {shape: "Incense burner fragments",},
    {shape: "Jar",},
    {shape: "Jar fragment",},
    {shape: "Jug",},
    {shape: "Jug fragment",},
    {shape: "Jug fragments",},
    {shape: "Kalathos",},
    {shape: "Kalathos(?) fragment",},
    {shape: "Kalathos fragment",},
    {shape: "Kalathos fragments",},
    {shape: "Kantharos",},
    {shape: "Kantharos(?) fragment",},
    {shape: "Kantharos fragment",},
    {shape: "Kantharos fragments",},
    {shape: "Kantharos, one handled",},
    {shape: "Kernos",},
    {shape: "Kernos fragment",},
    {shape: "Kernos fragment",},
    {shape: "Klepsydra",},
    {shape: "Kothon",},
    {shape: "Kotyle",},
    {shape: "Kotyle(?)",},
    {shape: "Kotyle fragment",},
    {shape: "Kotyle fragments",},
    {shape: "Kra ter(?) fragments",},
    {shape: "Krater",},
    {shape: "Krater(?) fr",},
    {shape: "Krater(?) fragment",},
    {shape: "Krater fragment",},
    {shape: "Krater fragment(?)",},
    {shape: "Krater fragments",},
    {shape: "Bell Krater",},
    {shape: "Krater, bell",},
    {shape: "Krater, bell",},
    {shape: "Krater, bell",},
    {shape: "Krater, bell(?)",},
    {shape: "Krater, bell(?) fragment",},
    {shape: "Krater, bell fragment",},
    {shape: "Krater, bell fragment",},
    {shape: "Krater, bell fragment",},
    {shape: "Krater, bell fragment",},
    {shape: "Krater, bell fragments",},
    {shape: "Calyx Krater",},
    {shape: "Krater, calyx",},
    {shape: "Krater, calyx(?) fragment",},
    {shape: "Krater, calyx(?) fragments",},
    {shape: "Krater, calyx fragment",},
    {shape: "Krater, calyx fragments",},
    {shape: "Krater, calyx, psykter",},
    {shape: "Krater, column",},
    {shape: "Krater, column(?)",},
    {shape: "Krater, column(?) fragment",},
    {shape: "Krater, column(?) fragments",},
    {shape: "Krater, column fragment",},
    {shape: "Krater, column fragments",},
    {shape: "Krater, column fragments",},
    {shape: "Krater, column, psykter",},
    {shape: "Krater, funnel",},
    {shape: "Krater, kantharoid",},
    {shape: "Krater, volute",},
    {shape: "Krater, volute(?) fragment",},
    {shape: "Krater, volute(?) fragments",},
    {shape: "Krater, volute fragment",},
    {shape: "Krater, volute fragments",},
    {shape: "Kyathos",},
    {shape: "Kyathos(?) fragment",},
    {shape: "Kyathos fragment",},
    {shape: "Kyathos fragments",},
    {shape: "Lagynos",},
    {shape: "Lagynos fragment",},
    {shape: "Lakaina",},
    {shape: "Lakaina fragment",},
    {shape: "Lamp",},
    {shape: "Lamp fragment",},
    {shape: "Lamp ring fragment",},
    {shape: "Lebes",},
    {shape: "Lebes(?) fragment",},
    {shape: "Lebes and lekanis",},
    {shape: "Lebes fragment",},
    {shape: "Lebes fragments",},
    {shape: "Lebes Gamikos",},
    {shape: "Lekanis",},
    {shape: "Lekanis(?) fragment",},
    {shape: "Lekanis fragment",},
    {shape: "Lekanis fragments",},
    {shape: "Lekanis lid",},
    {shape: "Lekanis lid(?) fragment",},
    {shape: "Lekanis lid fragment",},
    {shape: "Lekanis lid fragments",},
    {shape: "Lekanis with spout",},
    {shape: "Lekythos",},
    {shape: "Lekythos",},
    {shape: "Lekythos(?) fragment",},
    {shape: "Lekythos fragment",},
    {shape: "Lekythos fragments",},
    {shape: "Squat Lekythos",},
    {shape: "Lekythos,  squat",},
    {shape: "Lekythos, pagenstecher",},
    {shape: "Lekythos, pagenstecher",},
    {shape: "Lekythos, squat(?) fragment",},
    {shape: "Lekythos, squat(?) fragments",},
    {shape: "Lekythos, squat fragment",},
    {shape: "Lekythos, squat, fragments",},
    {shape: "Lepaste",},
    {shape: "Lid",},
    {shape: "Lid(?) fragment",},
    {shape: "Lid(?) frr",},
    {shape: "Lid fragment",},
    {shape: "Lid fragments",},
    {shape: "Loom weight",},
    {shape: "Louterion",},
    {shape: "Louterion fragment",},
    {shape: "Louterion frr",},
    {shape: "Loutrophoros",},
    {shape: "Loutrophoros(?)",},
    {shape: "Loutrophoros(?) fragment",},
    {shape: "Loutrophoros fragment",},
    {shape: "Loutrophoros fragments",},
    {shape: "Lydion",},
    {shape: "Mastoid",},
    {shape: "Mastoid(?) fragment",},
    {shape: "Mastoid fragment",},
    {shape: "Mastoid fragments",},
    {shape: "Mastos",},
    {shape: "Mastos(?)",},
    {shape: "Mastos fr",},
    {shape: "Mastos fragments",},
    {shape: "Medallion",},
    {shape: "Metron",},
    {shape: "Miniature panathenaic amphora",},
    {shape: "Mirror",},
    {shape: "Modiolus",},
    {shape: "Money box",},
    {shape: "Mould",},
    {shape: "Mould fragment",},
    {shape: "Mould fragments",},
    {shape: "Mug",},
    {shape: "Mug(?) fragment",},
    {shape: "Mug fragment",},
    {shape: "Mug fragments",},
    {shape: "Multiple cups",},
    {shape: "Nestoris",},
    {shape: "Nestoris fragments",},
    {shape: "Oin c  (Lek s ?) fr",},
    {shape: "Oin c(?) fr",},
    {shape: "Oinochoe",},
    {shape: "Oinochoe(?) fragment",},
    {shape: "Oinochoe(?) fragments",},
    {shape: "Oinochoe and lid",},
    {shape: "Oinochoe fragment",},
    {shape: "Oinochoe fragments",},
    {shape: "Oinochoe lid",},
    {shape: "Oinochoe(?) fragment",},
    {shape: "Oinochoe, beaked",},
    {shape: "Oinochoe, conical",},
    {shape: "Oinochoe, conical fragment",},
    {shape: "Oinophoros",},
    {shape: "Olla",},
    {shape: "Olla fragment",},
    {shape: "Olpe",},
    {shape: "Olpe(?)",},
    {shape: "Olpe(?) fragment",},
    {shape: "Olpe fragment",},
    {shape: "Olpe fragments",},
    {shape: "Oon",},
    {shape: "Oon fragment",},
    {shape: "Panathenaic amphora",},
    {shape: "Panathenaic amphora(?) fragment",},
    {shape: "Panathenaic amphora(?) fragments",},
    {shape: "Panathenaic amphora fragment",},
    {shape: "Panathenaic amphora fragments",},
    {shape: "Patera",},
    {shape: "Pelikai",},
    {shape: "Pelike",},
    {shape: "Pelike(?)",},
    {shape: "Pelike(?) fragment",},
    {shape: "Pelike(?) fragments",},
    {shape: "Pelike fragment",},
    {shape: "Pelike fragments",},
    {shape: "Phiale",},
    {shape: "Phiale fragment",},
    {shape: "Phiale fragments",},
    {shape: "Phormiskos",},
    {shape: "Phormiskos fragment",},
    {shape: "Phormiskos fragments",},
    {shape: "Pinax",},
    {shape: "Pinax fragment",},
    {shape: "Piriform jar",},
    {shape: "Pitcher",},
    {shape: "Pitcher fragment",},
    {shape: "Pithos",},
    {shape: "Pithos and lid",},
    {shape: "Pithos fragment",},
    {shape: "Plaque",},
    {shape: "Plaque(?) fr",},
    {shape: "Plaque(?) fragments",},
    {shape: "Plaque fragment",},
    {shape: "Plaque fragments",},
    {shape: "Plate",},
    {shape: "Plate(?) fragment",},
    {shape: "Plate(?) frr",},
    {shape: "Plate fragment",},
    {shape: "Plate fragments",},
    {shape: "Plate, stemmed",},
    {shape: "Plemochoe",},
    {shape: "Plemochoe fragment",},
    {shape: "Plemochoe fragments",},
    {shape: "Plemochoe type a",},
    {shape: "Plemochoe type b",},
    {shape: "Pomegranate",},
    {shape: "Pot",},
    {shape: "Pseudo panathenaic amphora",},
    {shape: "Pseudo panathenaic amphora fragments",},
    {shape: "Psykter",},
    {shape: "Psykter(?) fragments",},
    {shape: "Psykter fragment",},
    {shape: "Psykter fragments",},
    {shape: "Psykter-amphora, neck",},
    {shape: "Pyxis",},
    {shape: "Pyxis  frr",},
    {shape: "Pyxis(?) fragment",},
    {shape: "Pyxis(?) frr",},
    {shape: "Pyxis fragment",},
    {shape: "Pyxis fragments",},
    {shape: "Pyxis lid",},
    {shape: "Pyxis lid(?)",},
    {shape: "Pyxis lid(?) fr",},
    {shape: "Pyxis lid fragment",},
    {shape: "Pyxis lid fragments",},
    {shape: "Pyxis type a",},
    {shape: "Pyxis type c",},
    {shape: "Pyxis type d",},
    {shape: "Pyxis type d lid",},
    {shape: "Pyxis, tall",},
    {shape: "Rattle",},
    {shape: "Rhombos",},
    {shape: "Rhyton",},
    {shape: "Rhyton(?) fr",},
    {shape: "Rhyton fragment",},
    {shape: "Ring aryballos",},
    {shape: "Ring askos",},
    {shape: "Ring vase",},
    {shape: "Sacrificial basket",},
    {shape: "Sarcophagus",},
    {shape: "Sarcophagus fragment",},
    {shape: "Section Of Lid",},
    {shape: "Siphon vase",},
    {shape: "Situla",},
    {shape: "Situla fragment",},
    {shape: "Situla fragments",},
    {shape: "Skyphoi",},
    {shape: "Skyphoid Pyxides",},
    {shape: "Skyphoid Pyxis",},
    {shape: "Skyphos",},
    {shape: "Skyphos(?)",},
    {shape: "Skyphos(?) fragment",},
    {shape: "Skyphos(?) fragments",},
    {shape: "Skyphos fragment",},
    {shape: "Skyphos fragments",},
    {shape: "Skyphos krater",},
    {shape: "Skyphos krater fragment",},
    {shape: "Skyphos krater fragments",},
    {shape: "Spindle whorl",},
    {shape: "Spinning top",},
    {shape: "Spoon",},
    {shape: "Spouted vase",},
    {shape: "Sprinkler",},
    {shape: "Stamnos",},
    {shape: "Stamnos(?) fragment",},
    {shape: "Stamnos(?) fragments",},
    {shape: "Stamnos fragment",},
    {shape: "Stamnos fragments",},
    {shape: "Stamps",},
    {shape: "Stand",},
    {shape: "Stand(?) fragment",},
    {shape: "Stand(?) fragments",},
    {shape: "Stand fragment",},
    {shape: "Stand fragments",},
    {shape: "Stemless cup(?) fragments",},
    {shape: "Stemless cup fragment",},
    {shape: "Stirrup jar",},
    {shape: "Strainer",},
    {shape: "Tankard",},
    {shape: "Tile",},
    {shape: "Tray",},
    {shape: "Tray fragment",},
    {shape: "Triple-bodied vase",},
    {shape: "Tripod vase",},
    {shape: "Unguentarion",},
    {shape: "Urn",},
    {shape: "Urn fragments",},
    {shape: "Various",},
    {shape: "Vase",},
    {shape: "Well head",},
]